#############################################################################
# Makefile for building: salvador
# Generated by qmake (2.01a) (Qt 4.5.0) on: pon. wrz 21 05:01:13 2009
# Project:  salvador.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile salvador.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc/core -Isrc -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/test.cpp \
		src/core/sabstractgrid.cpp \
		src/core/sabstractmachine.cpp \
		src/core/sabstractpointer.cpp \
		src/core/scodegrid.cpp \
		src/core/scodeimagepointer.cpp \
		src/core/scodemachine.cpp \
		src/core/sdatagrid.cpp \
		src/core/sdataimagepointer.cpp \
		src/core/sdatamachine.cpp \
		src/core/svirtualmachine.cpp 
OBJECTS       = obj/test.o \
		obj/sabstractgrid.o \
		obj/sabstractmachine.o \
		obj/sabstractpointer.o \
		obj/scodegrid.o \
		obj/scodeimagepointer.o \
		obj/scodemachine.o \
		obj/sdatagrid.o \
		obj/sdataimagepointer.o \
		obj/sdatamachine.o \
		obj/svirtualmachine.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		salvador.pro
QMAKE_TARGET  = salvador
DESTDIR       = 
TARGET        = salvador

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: salvador.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile salvador.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile salvador.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/salvador1.0.0 || $(MKDIR) .tmp/salvador1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/salvador1.0.0/ && $(COPY_FILE) --parents src/debug.h src/core/sabstractgrid.h src/core/sabstractmachine.h src/core/sabstractpointer.h src/core/scodegrid.h src/core/scodeimagepointer.h src/core/scodemachine.h src/core/sdatagrid.h src/core/sdataimagepointer.h src/core/sdatamachine.h src/core/senums.h src/core/svirtualmachine.h .tmp/salvador1.0.0/ && $(COPY_FILE) --parents src/test.cpp src/core/sabstractgrid.cpp src/core/sabstractmachine.cpp src/core/sabstractpointer.cpp src/core/scodegrid.cpp src/core/scodeimagepointer.cpp src/core/scodemachine.cpp src/core/sdatagrid.cpp src/core/sdataimagepointer.cpp src/core/sdatamachine.cpp src/core/svirtualmachine.cpp .tmp/salvador1.0.0/ && (cd `dirname .tmp/salvador1.0.0` && $(TAR) salvador1.0.0.tar salvador1.0.0 && $(COMPRESS) salvador1.0.0.tar) && $(MOVE) `dirname .tmp/salvador1.0.0`/salvador1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/salvador1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/test.o: src/test.cpp src/core/svirtualmachine.h \
		src/core/senums.h \
		src/core/sdatamachine.h \
		src/core/sabstractmachine.h \
		src/core/sabstractpointer.h \
		src/core/sabstractgrid.h \
		src/core/sdataimagepointer.h \
		src/core/scodemachine.h \
		src/core/scodeimagepointer.h \
		src/core/scodegrid.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/test.o src/test.cpp

obj/sabstractgrid.o: src/core/sabstractgrid.cpp src/core/sabstractgrid.h \
		src/core/senums.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sabstractgrid.o src/core/sabstractgrid.cpp

obj/sabstractmachine.o: src/core/sabstractmachine.cpp src/core/sabstractmachine.h \
		src/core/senums.h \
		src/core/sabstractpointer.h \
		src/core/sabstractgrid.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sabstractmachine.o src/core/sabstractmachine.cpp

obj/sabstractpointer.o: src/core/sabstractpointer.cpp src/core/sabstractpointer.h \
		src/core/senums.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sabstractpointer.o src/core/sabstractpointer.cpp

obj/scodegrid.o: src/core/scodegrid.cpp src/core/scodegrid.h \
		src/core/senums.h \
		src/core/sabstractgrid.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scodegrid.o src/core/scodegrid.cpp

obj/scodeimagepointer.o: src/core/scodeimagepointer.cpp src/core/scodeimagepointer.h \
		src/core/senums.h \
		src/core/sabstractpointer.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scodeimagepointer.o src/core/scodeimagepointer.cpp

obj/scodemachine.o: src/core/scodemachine.cpp src/core/scodemachine.h \
		src/core/senums.h \
		src/core/sabstractmachine.h \
		src/core/sabstractpointer.h \
		src/core/sabstractgrid.h \
		src/core/scodeimagepointer.h \
		src/core/scodegrid.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scodemachine.o src/core/scodemachine.cpp

obj/sdatagrid.o: src/core/sdatagrid.cpp src/core/sdatagrid.h \
		src/core/senums.h \
		src/core/sabstractgrid.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sdatagrid.o src/core/sdatagrid.cpp

obj/sdataimagepointer.o: src/core/sdataimagepointer.cpp src/core/sdataimagepointer.h \
		src/core/senums.h \
		src/core/sabstractpointer.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sdataimagepointer.o src/core/sdataimagepointer.cpp

obj/sdatamachine.o: src/core/sdatamachine.cpp src/core/sdatamachine.h \
		src/core/senums.h \
		src/core/sabstractmachine.h \
		src/core/sabstractpointer.h \
		src/core/sabstractgrid.h \
		src/core/sdataimagepointer.h \
		src/debug.h \
		src/core/sdatagrid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sdatamachine.o src/core/sdatamachine.cpp

obj/svirtualmachine.o: src/core/svirtualmachine.cpp src/core/svirtualmachine.h \
		src/core/senums.h \
		src/core/sdatamachine.h \
		src/core/sabstractmachine.h \
		src/core/sabstractpointer.h \
		src/core/sabstractgrid.h \
		src/core/sdataimagepointer.h \
		src/core/scodemachine.h \
		src/core/scodeimagepointer.h \
		src/core/scodegrid.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/svirtualmachine.o src/core/svirtualmachine.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

